#pragma once

#include "driver/gpio.h"
#include "driver/spi_common.h"

/*
 * Board-profile defaults for ESP32-S3 runtime.
 * Override any macro from the build system or a board-specific header.
 */

#define GBA_STORAGE_MODE_SDMMC 1
#define GBA_STORAGE_MODE_SDSPI 2

#define GBA_DISPLAY_DRIVER_ST7735 1
#define GBA_DISPLAY_DRIVER_SSD1351 2

#define GBA_ROM_BACKEND_AUTO 0
#define GBA_ROM_BACKEND_SD_CACHE 1
#define GBA_ROM_BACKEND_FLASH_MMAP 2

#ifndef GBA_STORAGE_MODE
#define GBA_STORAGE_MODE GBA_STORAGE_MODE_SDSPI
#endif

#ifndef GBA_DISPLAY_DRIVER
#define GBA_DISPLAY_DRIVER GBA_DISPLAY_DRIVER_ST7735
#endif

#ifndef GBA_ROM_BACKEND
#define GBA_ROM_BACKEND GBA_ROM_BACKEND_SD_CACHE
#endif

#ifndef GBA_ROM_SD_CACHE_BYTES
#define GBA_ROM_SD_CACHE_BYTES (2 * 1024 * 1024)
#endif

#ifndef GBA_ROM_SD_CACHE_PAGE_BYTES
#define GBA_ROM_SD_CACHE_PAGE_BYTES (32 * 1024)
#endif

#ifndef GBA_ROM_MMAP_PARTITION_LABEL
#define GBA_ROM_MMAP_PARTITION_LABEL "gba_rom"
#endif

#ifndef GBA_ROM_MMAP_WINDOW_BYTES
#define GBA_ROM_MMAP_WINDOW_BYTES (64 * 1024)
#endif

#ifndef GBA_ROM_MMAP_WINDOW_COUNT
#define GBA_ROM_MMAP_WINDOW_COUNT 16
#endif

/* Display (SPI LCD/OLED) */
#ifndef GBA_DISPLAY_PIN_SCLK
#define GBA_DISPLAY_PIN_SCLK GPIO_NUM_4
#endif
#ifndef GBA_DISPLAY_PIN_MOSI
#define GBA_DISPLAY_PIN_MOSI GPIO_NUM_5
#endif
#ifndef GBA_DISPLAY_PIN_DC
#define GBA_DISPLAY_PIN_DC GPIO_NUM_6
#endif
#ifndef GBA_DISPLAY_PIN_CS
#define GBA_DISPLAY_PIN_CS GPIO_NUM_7
#endif
#ifndef GBA_DISPLAY_PIN_RST
#define GBA_DISPLAY_PIN_RST GPIO_NUM_8
#endif
#ifndef GBA_DISPLAY_PIN_BL
#define GBA_DISPLAY_PIN_BL GPIO_NUM_9
#endif

#ifndef GBA_DISPLAY_WIDTH
#define GBA_DISPLAY_WIDTH 128
#endif

#ifndef GBA_DISPLAY_HEIGHT
#if GBA_DISPLAY_DRIVER == GBA_DISPLAY_DRIVER_SSD1351
#define GBA_DISPLAY_HEIGHT 96
#else
#define GBA_DISPLAY_HEIGHT 128
#endif
#endif

#ifndef GBA_DISPLAY_COL_OFFSET
#if GBA_DISPLAY_DRIVER == GBA_DISPLAY_DRIVER_ST7735
#define GBA_DISPLAY_COL_OFFSET 2
#else
#define GBA_DISPLAY_COL_OFFSET 0
#endif
#endif

#ifndef GBA_DISPLAY_ROW_OFFSET
#if GBA_DISPLAY_DRIVER == GBA_DISPLAY_DRIVER_ST7735
#define GBA_DISPLAY_ROW_OFFSET 1
#else
#define GBA_DISPLAY_ROW_OFFSET 0
#endif
#endif

#ifndef GBA_DISPLAY_SPI_CLK_HZ
#if GBA_DISPLAY_DRIVER == GBA_DISPLAY_DRIVER_SSD1351
#define GBA_DISPLAY_SPI_CLK_HZ (8 * 1000 * 1000)
#else
#define GBA_DISPLAY_SPI_CLK_HZ (26 * 1000 * 1000)
#endif
#endif

#ifndef GBA_DISPLAY_SWAP_BYTES
#if GBA_DISPLAY_DRIVER == GBA_DISPLAY_DRIVER_SSD1351
#define GBA_DISPLAY_SWAP_BYTES 1
#else
#define GBA_DISPLAY_SWAP_BYTES 0
#endif
#endif

#ifndef GBA_DISPLAY_SSD1351_MUX_RATIO
#define GBA_DISPLAY_SSD1351_MUX_RATIO 127
#endif

#ifndef GBA_DISPLAY_SSD1351_STARTLINE
#if GBA_DISPLAY_DRIVER == GBA_DISPLAY_DRIVER_SSD1351 && GBA_DISPLAY_HEIGHT < 128
#define GBA_DISPLAY_SSD1351_STARTLINE 96
#else
#define GBA_DISPLAY_SSD1351_STARTLINE 0
#endif
#endif

/* SDMMC 4-bit mode */
#ifndef GBA_SDMMC_PIN_CLK
#define GBA_SDMMC_PIN_CLK GPIO_NUM_14
#endif
#ifndef GBA_SDMMC_PIN_CMD
#define GBA_SDMMC_PIN_CMD GPIO_NUM_15
#endif
#ifndef GBA_SDMMC_PIN_D0
#define GBA_SDMMC_PIN_D0 GPIO_NUM_2
#endif
#ifndef GBA_SDMMC_PIN_D1
#define GBA_SDMMC_PIN_D1 GPIO_NUM_17
#endif
#ifndef GBA_SDMMC_PIN_D2
#define GBA_SDMMC_PIN_D2 GPIO_NUM_12
#endif
#ifndef GBA_SDMMC_PIN_D3
#define GBA_SDMMC_PIN_D3 GPIO_NUM_13
#endif

/* SDSPI mode */
#ifndef GBA_SDSPI_HOST
#define GBA_SDSPI_HOST SPI3_HOST
#endif
#ifndef GBA_SDSPI_PIN_MISO
#define GBA_SDSPI_PIN_MISO GPIO_NUM_12
#endif
#ifndef GBA_SDSPI_PIN_MOSI
#define GBA_SDSPI_PIN_MOSI GPIO_NUM_13
#endif
#ifndef GBA_SDSPI_PIN_SCLK
#define GBA_SDSPI_PIN_SCLK GPIO_NUM_14
#endif
#ifndef GBA_SDSPI_PIN_CS
#define GBA_SDSPI_PIN_CS GPIO_NUM_15
#endif

/* Input: active-low buttons with internal pull-ups. */
#ifndef GBA_INPUT_PIN_A
#define GBA_INPUT_PIN_A GPIO_NUM_10
#endif
#ifndef GBA_INPUT_PIN_B
#define GBA_INPUT_PIN_B GPIO_NUM_11
#endif
#ifndef GBA_INPUT_PIN_SELECT
#define GBA_INPUT_PIN_SELECT GPIO_NUM_16
#endif
#ifndef GBA_INPUT_PIN_START
#define GBA_INPUT_PIN_START GPIO_NUM_18
#endif
#ifndef GBA_INPUT_PIN_RIGHT
#define GBA_INPUT_PIN_RIGHT GPIO_NUM_38
#endif
#ifndef GBA_INPUT_PIN_LEFT
#define GBA_INPUT_PIN_LEFT GPIO_NUM_39
#endif
#ifndef GBA_INPUT_PIN_UP
#define GBA_INPUT_PIN_UP GPIO_NUM_40
#endif
#ifndef GBA_INPUT_PIN_DOWN
#define GBA_INPUT_PIN_DOWN GPIO_NUM_41
#endif
#ifndef GBA_INPUT_PIN_R
#define GBA_INPUT_PIN_R GPIO_NUM_42
#endif
#ifndef GBA_INPUT_PIN_L
#define GBA_INPUT_PIN_L GPIO_NUM_21
#endif

/* Audio: MAX98357A I2S mono Class-D amplifier */
#ifndef GBA_AUDIO_PIN_BCK
#define GBA_AUDIO_PIN_BCK GPIO_NUM_35
#endif
#ifndef GBA_AUDIO_PIN_WS
#define GBA_AUDIO_PIN_WS GPIO_NUM_36
#endif
#ifndef GBA_AUDIO_PIN_DOUT
#define GBA_AUDIO_PIN_DOUT GPIO_NUM_37
#endif
